config/routes.rb
Rails.application.routes.draw do
  resources :sightings do
    get :get_sightings, on: :collection
  end

  root "sightings#index"
  resources :animals

  get 'calendar' => 'sightings#calendar'

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :sightings
  validates :name, :latin_name, :kingdom, length:{in: 3..20}, presence: true
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :animal
  validates :latitude, :longitude, numericality: true
  validate :no_future_date

  def no_future_date
    if date > Date.today
      errors.add(:date, "future dates invalid .")
    end
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
    # @count = Animal.count(:conditions => "name = Bear")
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  # GET /sightings
  # GET /sightings.json
  def index
    if params[:start_date].present?
      @sightings = Sighting.where(date: params[:start_date]..params[:end_date])
      render('sightings/index.html.erb')
    elsif params[:region].present?
      @sightings = Sighting.where(region: params[:region])
      render('sightings/index.html.erb')
    else
      @sightings = Sighting.all
    end
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
    if params[:animal_id].present?
      @sighting.animal = Animal.find(params[:animal_id])
    end
    @animals_for_select = Animal.all.map do |animal|
      [animal.name, animal.id]
    end


  end

  # GET /sightings/1/edit
  def edit
    @animals_for_select = Animal.all.map do |animal|
      [animal.name, animal.id]
    end
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)
    @animals_for_select = Animal.all.map do |animal|
      [animal.name, animal.id]
    end

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def calendar
  end

  def get_sightings
    @sightings = Sighting.all
    events = []
    @sightings.each do |sighting|
      events << { title: sighting.animal.name+"/"+sighting.region, start: sighting.date, allDay: true, time: sighting.time, latitude: sighting.latitude, longitude: sighting.longitude, region: sighting.region }
    end
    render :json => events.to_json

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:animal_id, :date, :time, :latitude, :longitude, :region)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latin_name %><br>
    <%= f.text_field :latin_name %>
  </div>
  <div class="field">
    <%= f.label :kingdom %><br>
    <%= f.text_field :kingdom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Animals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latin name</th>
      <th>Kingdom</th>
      <th># of Sightings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.latin_name %></td>
        <td><%= animal.kingdom %></td>
        <td style="text-align: center"><%=link_to animal.sightings.count, animal_path(animal.id) %></td>
        <!-- <td><%= link_to 'Show', animal %></td> -->
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>
<%= link_to 'Sightings List', sightings_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Latin name:</strong>
  <%= @animal.latin_name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @animal.kingdom %>
</p>

<p>
  <strong>Sightings:</strong>
  <ul>
    <% @animal.sightings.each do |sighting| %>
    <li>
       <%=sighting.date%> | <%=sighting.time.strftime("%I:%M%P")%> | <%=sighting.longitude%> | <%=sighting.latitude%>
    </li>
    <%end%>
  </ul>
</p>

<%= link_to 'Add Sighting', new_sighting_path() + "?animal_id=" + @animal.id.to_s %>
<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wildapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= form_for(@sighting) do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :animal_id %><br>
    <%= select(:sighting, :animal_id, @animals_for_select) %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :region %><br>
    <%= select(:sighting, :region, [["Downtown Portland"], ["OldTown ChinaTown"],["Pearl District"], ["Lloyd District"], ["Mississippi/Williams"]]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sightings/calendar.html.erb
<%=link_to 'Animal Sightings', sightings_path%>
<br>
<br>
<div id="calendar_css">
    <div id="calendar"></div>
</div>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form' %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sightings</h1>

<h2>Filters:</h2>
<h3>Date</h3>
<form action="/sightings" method="get">
  <label for="start_date">Start Date</label>
  <input id="start_date" type="text" name="start_date">
  <label for="end_date">End Date</label>
  <input id="end_date" type="text" name="end_date">
  <button>Apply Date Filter</button>
</form>

<h3>Region</h3>
<form action="/sightings" method="get">
  <label for="region">Region</label>
  <select name="region">
    <option value="Downtown Portland">Downtown Portland</option>
    <option value="OldTown ChinaTown">OldTown ChinaTown</option>
    <option value="Pearl District">Pearl District</option>
    <option value="Lloyd District">Lloyd District</option>
    <option value="Mississippi/Williams">Mississippi/Williams</option>
</select>
  <button>Apply Region Filter</button>
</form>
<br>
<%=button_to "Remove Filter", sightings_path, method: :get %>
<br>
<table>
  <thead>
    <tr>
      <th>Animal</th>
      <th>Date</th>
      <th>Time</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Region</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.animal.name %></td>
        <td><%= sighting.date %></td>
        <td><%= sighting.time.strftime("%I:%M%P") %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= sighting.region %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Sighting', new_sighting_path %>
<%= link_to 'Animal List', animals_path %>
<%= link_to 'Sightings Calendar', calendar_path %>

app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form' %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Animal:</strong>
  <%= @sighting.animal.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @sighting.time.strftime("%I:%M%P") %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Region:</strong>
  <%= @sighting.region %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>